# -*- mode: python ; coding: utf-8 -*-
# Copyright 2026 Christian Guyot
# SPDX-License-Identifier: Apache-2.0
"""
PyInstaller spec -- PixelPhotoManager
Build:  .venv\\Scripts\\pyinstaller.exe pixelphotomanager.spec --clean
Output: dist\\PixelPhotoManager\\PixelPhotoManager.exe  (one-dir)
"""
from PyInstaller.utils.hooks import collect_all
from pathlib import Path
import insightface
import PySide6

ROOT = Path(SPECPATH)

# Packages with embedded resources (templates, fonts, plugins)
# pillow_heif/rawpy: native DLLs (libheif, libraw) embedded through
# collect_all -- never in excludes (cf. src/library/image_loader.py,
# the single RAW/HEIC decoding point).
_with_data = ["PIL", "folium", "reportlab", "insightface", "pillow_heif", "rawpy"]

datas, binaries, hiddenimports = [], [], []
for pkg in _with_data:
    d, b, h = collect_all(pkg)
    datas += d
    binaries += b
    hiddenimports += h

# insightface.data.get_object() (pickle_object.py) resolves its resources
# differently in frozen mode: in "frozen" mode, it reads
# sys._MEIPASS/objects/<name>.pkl -- an "objects" folder AT THE ROOT of the
# bundle -- and NOT insightface/data/objects/ (the normal tree of the
# package, which collect_all() above preserves). Without that extra
# copy, get_object('meanshape_68.pkl') returns None silently
# (just a print(), invisible with console=False), and the
# landmark_3d_68 model (pose estimation) crashes with
# 'NoneType' object has no attribute 'shape' inside
# transform.estimate_affine_matrix_3d23d() -- for EVERY detected face.
_insightface_objects_dir = Path(insightface.__file__).parent / "data" / "objects"
datas += [(str(_insightface_objects_dir), "objects")]

# The buffalo_l model pack (detection + embedding) embedded in the exe so as
# to avoid the download (~340 MB) from GitHub on the 1st launch -- on a
# machine with no Internet access (or a firewall blocking github.com), face
# detection was otherwise completely inoperative. Placed at the root of the bundle
# under "insightface_root/models/buffalo_l"; src/faces/detector.py points
# FaceAnalysis(root=...) explicitly at it in frozen mode (sys._MEIPASS).
# Requires the application to have been run at least once in dev mode so that the
# pack is present in the user cache (~/.insightface/models/buffalo_l).
_buffalo_l_dir = Path.home() / ".insightface" / "models" / "buffalo_l"
if not _buffalo_l_dir.is_dir():
    raise FileNotFoundError(
        f"Pack de modèles buffalo_l introuvable : {_buffalo_l_dir}\n"
        "Lancez l'appli une fois en mode dev (avec accès Internet) pour "
        "déclencher le téléchargement automatique, puis relancez le build."
    )
datas += [(str(_buffalo_l_dir), "insightface_root/models/buffalo_l")]

# Content of the help tabs (src/ui/help_content/<language>/*.html) -- resolved in
# frozen mode through sys._MEIPASS/help_content (cf. src/ui/help_dialog.py::_content_dir).
# A "folder" datas entry is copied recursively: the language
# subfolders (fr/en/de) follow with no dedicated entry.
datas += [("src/ui/help_content", "help_content")]

# Version number embedded at the root of the bundle (sys._MEIPASS/VERSION), read
# by src/core/app_version.py::get_app_version() in frozen mode (the .git folder
# is not available inside the exe to run a "git describe"). The
# VERSION file at the root of the repository is updated by build.ps1 before every build,
# from the version number asked of the builder.
_version_file = ROOT / "VERSION"
if not _version_file.is_file():
    raise FileNotFoundError(
        f"Fichier VERSION introuvable : {_version_file}\n"
        "Lancez le build via build.ps1 (qui le génère) plutôt que pyinstaller directement."
    )
datas += [(str(_version_file), ".")]

# Compiled translation catalogs (translations/ppm_*.qm) plus those of Qt itself
# (qtbase_*.qm: OK/Cancel buttons, file selector…), both resolved by
# src/core/i18n.py under sys._MEIPASS/translations in frozen mode. The .qm files are
# generated by tools/update_translations.py -- a .ts with no .qm is of no use at
# runtime, hence the explicit failure rather than a silently English interface.
_ts_dir = ROOT / "translations"
_qm_files = sorted(_ts_dir.glob("ppm_*.qm")) if _ts_dir.is_dir() else []
if not _qm_files:
    raise FileNotFoundError(
        f"Aucun catalogue compilé dans {_ts_dir}\n"
        "Lancez : .venv\\Scripts\\python.exe tools\\update_translations.py"
    )
datas += [(str(p), "translations") for p in _qm_files]

_qt_ts_dir = Path(PySide6.__file__).parent / "translations"
for _code in ("fr", "en", "de"):
    _qtbase = _qt_ts_dir / f"qtbase_{_code}.qm"
    if _qtbase.is_file():
        datas += [(str(_qtbase), "translations")]

a = Analysis(
    [str(ROOT / "main.py")],
    pathex=[str(ROOT)],
    binaries=binaries,
    datas=datas + [
        (str(ROOT / "assets"), "assets"),
    ],
    hiddenimports=hiddenimports + [
        # Pillow -- image plugins loaded dynamically
        "PIL.Image", "PIL.ImageOps", "PIL.ImageFilter", "PIL.ImageDraw",
        "PIL.JpegImagePlugin", "PIL.Jpeg2KImagePlugin",
        "PIL.PngImagePlugin",  "PIL.TiffImagePlugin",
        "PIL.WebPImagePlugin", "PIL.BmpImagePlugin",
        "PIL.GifImagePlugin",  "PIL.IcoImagePlugin",
        # OpenCV (DLLs handled by the hooks-contrib hook)
        "cv2",
        # EXIF
        "piexif",
        # Perceptual hashing (duplicate detection)
        "imagehash",
        # Windows recycle bin (src/library/trash.py)
        "send2trash",
        # Stdlib (SQLite is embedded in Python, but the inclusion is forced)
        "sqlite3", "_sqlite3",
        # Encodings used by the logging / the Windows paths
        "encodings.utf_8", "encodings.cp1252",
    ],
    hookspath=[],
    hooksconfig={
        # PySide6: include the required Qt plugins
        "PySide6": {
            "qt_plugins": [
                "platforms",        # QWindowsIntegration (mandatory)
                "imageformats",     # JPEG, PNG, TIFF, WebP in Qt
                "styles",           # QWindowsVistaStyle
                "iconengines",      # SVG icons
            ],
        },
    },
    runtime_hooks=[],
    excludes=[
        # Heavy AI dependencies -- not used in the base build
        # (sklearn/scikit_learn MUST NOT be excluded: required by hdbscan for face
        # clustering, cf. src/faces/clusterer.py)
        "deepface", "retinaface",
        "torch", "torchvision", "torchaudio",
        "tensorflow", "tensorboard", "keras",
        # Useless in production
        "tkinter",
        "matplotlib",
        "IPython", "jupyter", "notebook",
        "debugpy",
        "pytest",
    ],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="PixelPhotoManager",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,          # UPX disabled: avoids antivirus false positives
    console=False,      # No console window (a graphical application)
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=str(ROOT / "assets" / "app_icon.ico"),
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name="PixelPhotoManager",
)
