# Copyright 2026 Christian Guyot
# SPDX-License-Identifier: Apache-2.0
"""Internationalisation: English (source language), French, German.

English is the language of the strings written in the code: any untranslated
string therefore falls back automatically on correct English, whatever the
interface language. It still has its own catalogue, but for a single purpose:
**plurals**. A `%n` string is written in the code in a neutral form ("%n
face(s)") since the same literal must serve both singular and plural; it is
`ppm_en.qm` that carries the two real forms ("%n face" / "%n faces"). The
other messages stay empty there and fall back on the source.

The `.ts` (sources, versioned) and `.qm` (compiled, loaded at runtime)
catalogues live in `translations/` at the root of the repository and are
regenerated by `tools/update_translations.py`.

Two translators are installed per language:

- `ppm_<code>.qm` — the strings of the application;
- `qtbase_<code>.qm` — those of Qt itself (the OK/Cancel buttons of the
  QMessageBox dialogs, the file picker, the context menu of input fields).
  Without it, a German interface keeps its standard dialogs in English.
  It is loaded for French too, which Qt does not speak by default.

A language change takes effect on restart: widgets build their labels once,
there is no `retranslate_ui()`.

Marking strings — a single form in the whole project ::

    from src.core.i18n import translate
    ...
    translate("MainWindow", "Displayed text")

`translate` is `QCoreApplication.translate`; `pyside6-lupdate` recognises that
name as such, including when imported from here (test: `tests/test_i18n.py`).

**Do not use `self.tr()`**: PySide6 resolves its context on the class of the
*instance*, not on the one that writes the call, whereas `lupdate` extracts it
under the class that writes it. The two diverge as soon as a class is
inherited — and the mixins of `MainWindow` (`main_window_faces.py`,
`main_window_duplicates.py`) are in that case: extraction under
"MainWindowFacesMixin", lookup at runtime under "MainWindow", hence a label
never translated, silently. The literal context of `translate()` removes the
question: one writes the name of the **runtime** class there ("MainWindow" for
a MainWindow mixin).
"""

import logging
import sys
from pathlib import Path

from PySide6.QtCore import QCoreApplication, QLibraryInfo, QLocale, QTranslator

logger = logging.getLogger(__name__)

#: Fallback language: that of the source strings written in the code. A message
#: with no translation is therefore displayed in English, never empty.
DEFAULT_LANGUAGE = "en"

#: Supported ISO 639-1 codes -> the name of the language in that language
#: (a user who has put the application into a language they cannot read must
#: be able to find their own in the list).
LANGUAGES: dict[str, str] = {
    "en": "English",
    "fr": "Français",
    "de": "Deutsch",
}

CONFIG_KEY = "ui.language"

#: Marker for a translatable string — cf. the module docstring.
#: Qt signature: translate(context, source, disambiguation=None, n=-1).
translate = QCoreApplication.translate

# The QTranslator objects must outlive the call: Qt only keeps a weak
# reference on the Python side, and a collected translator silently stops
# translating.
_installed: list[QTranslator] = []

#: Language actually installed by `install()` (cf. `active_language`).
_active: str = DEFAULT_LANGUAGE


def app_translations_dir() -> Path:
    """Folder of the application `.qm` files."""
    if getattr(sys, "frozen", False):
        return Path(getattr(sys, "_MEIPASS", "")) / "translations"
    return Path(__file__).resolve().parent.parent.parent / "translations"


def _qt_translations_dirs() -> list[Path]:
    """Folders where to look for the Qt `.qm` files (qtbase_*).

    QLibraryInfo is enough in dev mode. In frozen mode it may point to the path
    of the build machine: we therefore add the real location inside the bundle.
    """
    dirs = [Path(QLibraryInfo.path(QLibraryInfo.LibraryPath.TranslationsPath))]
    if getattr(sys, "frozen", False):
        meipass = Path(getattr(sys, "_MEIPASS", ""))
        dirs += [meipass / "PySide6" / "translations", meipass / "translations"]
    return dirs


def _bare_code(value) -> str:
    """"fr_FR", "fr-FR", "FR" -> "fr". Empty string if nothing usable."""
    return str(value or "").strip().replace("-", "_").split("_")[0].lower()


def normalize(code: str | None) -> str:
    """Brings any config value back to a supported code."""
    bare = _bare_code(code)
    return bare if bare in LANGUAGES else DEFAULT_LANGUAGE


def system_language() -> str:
    """The system language if it is supported, otherwise `DEFAULT_LANGUAGE`.

    Goes through `_bare_code` and not through `normalize`: the latter folds
    every unknown code onto `DEFAULT_LANGUAGE`, which would make "system in
    Japanese" indistinguishable from "system in English" and would stop the
    walk through the languages on the first one that comes.

    Deliberately **not** used as the default value: the language of the Windows
    interface does not tell which language the user wants to read (a real case:
    Windows in English, application always used in French). Such a setting
    would have switched the interface of existing installations without anyone
    asking for it. Exposed for a possible explicit "detect automatically" in
    the settings.
    """
    for name in QLocale.system().uiLanguages():
        code = _bare_code(name)
        if code in LANGUAGES:
            return code
    return DEFAULT_LANGUAGE


#: Registry value written by the MSI installer (cf. `installer/product.wxs`):
#: the code of the language it displayed itself, therefore the one Windows
#: selected from the machine language.
_INSTALL_KEY = r"SOFTWARE\PixelPhotoManager"
_INSTALL_VALUE = "InstallLanguage"


def installer_language() -> str | None:
    """Language pre-positioned by the installer, `None` if there is none.

    The installer is the only piece that knows, at that point, which language
    the machine speaks: Windows picks one of the embedded transforms on its own
    and the installer writes the corresponding code down. Without that, an
    application installed in French would still start in English until its user
    found the setting.

    `None` rather than `DEFAULT_LANGUAGE` when the value is absent or
    unsupported, so that "no installer" (a run from the sources, a portable
    copy, another OS) stays distinguishable from "installer in English" —
    only the caller decides what to do with it (cf. `src/core/config.py`, which
    consults it solely when it has no configuration yet).
    """
    if sys.platform != "win32":
        return None
    try:
        import winreg

        with winreg.OpenKey(winreg.HKEY_LOCAL_MACHINE, _INSTALL_KEY) as key:
            value, _ = winreg.QueryValueEx(key, _INSTALL_VALUE)
    except OSError:
        return None
    except Exception as exc:  # pragma: no cover - defensive
        logger.debug(f"Lecture InstallLanguage impossible : {exc}")
        return None
    code = _bare_code(value)
    return code if code in LANGUAGES else None


def current_language(config) -> str:
    """Language chosen by the user, English failing that (cf. above)."""
    return normalize(config.get(CONFIG_KEY))


def set_language(config, code: str) -> None:
    config.set(CONFIG_KEY, normalize(code))


def active_language() -> str:
    """Language actually installed by `install()`.

    To be used for any content resolved by language outside the Qt catalogues
    (the built-in help, cf. `src/ui/help_dialog.py`): the config value may
    already carry the user's next choice, while the displayed interface is
    still in the previous language until the restart.
    """
    return _active


def install(app: QCoreApplication, code: str) -> str:
    """Installs the translators for `code`. Returns the language really set.

    To be called right after the QApplication is created, before the least
    widget is built: a label already displayed does not get retranslated.
    """
    global _active
    code = normalize(code)
    _active = code
    for tr in _installed:
        app.removeTranslator(tr)
    _installed.clear()

    qm = app_translations_dir() / f"ppm_{code}.qm"
    translator = QTranslator()
    if qm.is_file() and translator.load(str(qm)):
        app.installTranslator(translator)
        _installed.append(translator)
    elif code != DEFAULT_LANGUAGE:
        # Silent fallback on English rather than an empty interface: the source
        # strings stay displayed as they are. No warning for `DEFAULT_LANGUAGE`
        # itself: its catalogue only carries the plurals, so its absence degrades
        # "3 photos" into "3 photo(s)", nothing more.
        logger.warning("Catalogue de traduction introuvable ou illisible : %s", qm)

    _install_qt_base(app, code)
    return code


def _install_qt_base(app: QCoreApplication, code: str) -> None:
    for directory in _qt_translations_dirs():
        translator = QTranslator()
        if translator.load(f"qtbase_{code}", str(directory)):
            app.installTranslator(translator)
            _installed.append(translator)
            return
    logger.debug("qtbase_%s.qm introuvable — dialogues standard Qt en anglais", code)
